from setuptools import setup, find_packages

setup(
    name="enterprise-scraping-system",
    version="1.0.0",
    description="Enterprise-grade distributed web scraping system",
    author="Enterprise Team",
    packages=find_packages(),
    install_requires=[
        "fastapi==0.104.1",
        "uvicorn[standard]==0.24.0",
        "pydantic==2.5.0",
        "pydantic-settings==2.1.0",
        "aiohttp==3.9.1",
        "httpx==0.25.2",
        "playwright==1.40.0",
        "scrapy==2.11.0",
        "beautifulsoup4==4.12.2",
        "lxml==4.9.3",
        "motor==3.4.0",
        "redis==5.0.1",
        "kafka-python==2.0.2",
        "python-jose[cryptography]==3.3.0",
        "passlib[bcrypt]==1.7.4",
        "python-multipart==0.0.6",
        "cryptography==41.0.7",
        "python-dotenv==1.0.0",
        "python-json-logger==2.0.7",
        "loguru==0.7.2",
        "pydantic-extra-types==2.5.0",
        "prometheus-client==0.19.0",
        "apscheduler==3.10.4",
        "pandas==2.1.3",
        "numpy==1.26.2",
        "fake-useragent==1.4.0",
    ],
    python_requires=">=3.11",
)